app:
  hello:
    greeting: Ahoj
  current-account:
    transaction:
      get-latest-current-account-transactions-max-record-count: 20
  integration:
    fees:
      base-uri: http://localhost:1080
      username: dummy
      password: dummy
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cvicenie_docker?currentSchema=cvicenie_docker
    username: cvicenie_docker
    password: cvicenie_docker

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    java:
      enabled: true
